sudo: required
dist: xenial
language: c
compiler:
  - gcc
before_install:
  - sudo apt-get install xvfb
  - sudo apt-get install arduino-mk
  - sudo apt-get install ruby ruby-qt4 ruby-dev ruby-serialport
  - sudo apt-get install libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
  - sudo gem install rspec
  - sudo gem install ruby-sdl2
  - wget -c https://github.com/google/googletest/archive/release-1.7.0.tar.gz -O googletest-release-1.7.0.tar.gz
  - tar xzf googletest-release-1.7.0.tar.gz
  - wget -c https://github.com/google/googlemock/archive/release-1.7.0.tar.gz -O googlemock-release-1.7.0.tar.gz
  - tar xzf googlemock-release-1.7.0.tar.gz
install:
  - cp calibration.hh.default calibration.hh
  - env PATH=/usr/share/arduino:$PATH make all-recursive
script:
  - xvfb-run make GTEST=googletest-release-1.7.0 GMOCK=googlemock-release-1.7.0 check
