version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
        - name: install dependencies
        - command: sudo apt-get install arduino-mk
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
        - name: run tests
        - command: make check

workflows:
  version: 2.0
  build_and_test:
    jobs:
      - build
      - test:
        - requires:
          - build
        - filters:
          branches:
            only: master
