version: 2.0
jobs:
  build-and-test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
        - name: install dependencies
        - command: sudo apt-get install arduino-mk

workflows:
  version: 2.0
  build-test:
    jobs:
      - build-and-test
